import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

#///////////////////////////////////////////////////////////////
#DISCLAIMER:
#I did not make this code, it was generated by chatGPT as an example to 
#help me understand how the code is implemented
#///////////////////////////////////////////////////////////////

class textDataset(Dataset):
    def __init__(self, text, block_size):
        chars = sorted(list(set(text)))
        self.stoi = {ch : i for i, ch in enumerate(chars)}
        self.itos = {i : ch for i, ch in enumerate(chars)}
        self.vocabSize = len(chars)

        self.data = [self.stoi[c] for c in text]
        self.blockSize = block_size

    def __len__(self):
        return len(self.data) - self.blockSize
    
    def __getitem__(self, idx):
        x = torch.tensor(self.data[idx : idx + self.blockSize], dtype = torch.long)
        y = torch.tensor(self.data[idx + 1 : idx + self.blockSize + 1], dtype = torch.long)
        return x, y


class multiHeadSelfAttention(nn.Module):
    def __init__(self, embed_size, num_heads, block_size):
        super.__init__()
        self.numHeads = num_heads
        self.headDim = embed_size // num_heads
        assert self.headDim * num_heads == embed_size, 'embed_size must be divisible by num_heads'

    def forward(self, x):
        B, T, C = x.shape
        Q = self.query(x).view(B, T, self.numHeads, self.headDim).transpose(1, 2)
        K = self.key(x).view(B, T, self.numHeads, self.headDim).transpose(1, 2)
        V = self.value(x).view(B, T, self.numHeads, self.headDim).transpose(1, 2)

        scores = (Q @ K.transpose(-2, -1)) / (self.headDim ** 0.5)
        mask = self.mask[:, :, :T, :T]
        scores = scores.masked_fill(mask == 0, float("-inf"))

        attn = F.softmax(scores, dim = -1)
        out = attn @ V

        out = out.transpose(1, 2).contiguous().view(B, T, C)
        return self.fc_out(out)
    

class transformerBlock(nn.module):
    def __init__(self, embed_size, num_heads, block_size, forward_expansion = 4, dropout = 0.1):
        super().__init__()
        self.attn = multiHeadSelfAttention(embed_size, num_heads, block_size)
        self.norm1 = nn.LayerNorm(embed_size)
        self.norm2 = nn.LayerNorm(embed_size)
        self.feedForward = nn.Sequential(
            nn.Linear(embed_size, forward_expansion * embed_size),
            nn.ReLU(),
            nn.Linear(forward_expansion * embed_size, embed_size)
        )
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        x = x + self.dropout(self.attn(self.norm1(x)))
        x = x + self.dropout(self.feedForward(self.norm2(x)))
        return x
    

class miniGPT(nn.Module):
    def __init__(self, vocab_size, embed_size, block_size, num_heads, num_layers):
        super().__init__()
        self.blockSize = block_size
        self.embed = nn.Embedding(vocab_size, embed_size)
        self.posEmbed = nn.Embedding(block_size, embed_size)

        #self.layers (complete later)